sudo: required
services:
  - docker

before_install:
  - docker build -t johnrattz/react-test -f ./client/Dockerfile.dev ./client

# Testing running section. If any command returns a value other than 0, TravisCI considers the build failed.
#script: # The tests run by `react-test npm test` fail with a "Network Error" for reasons unknown to me (not a React developer).
#  - docker run -t johnrattz/react-test npm test -- --coverage

after_success:
  - docker build -t johnrattz/multi-client ./client
  - docker build -t johnrattz/multi-nginx ./nginx
  - docker build -t johnrattz/multi-server ./server
  - docker build -t johnrattz/multi-worker ./worker
  # Log in to the Docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub.
  - docker push johnrattz/multi-client
  - docker push johnrattz/multi-nginx
  - docker push johnrattz/multi-server
  - docker push johnrattz/multi-worker