sudo: required
services:
  - docker

before_install:
  - docker build -t johnrattz/react-test -f ./client/Dockerfile.dev ./client

# Testing running section. If any command returns a value other than 0, TravisCI considers the build failed.
script: # The tests run by `react-test npm test` fail with a "Network Error" for reasons unknown to me (not a React developer).
#  - docker run -t johnrattz/react-test npm test -- --coverage
  - $(exit 0)

after_success:
  - docker build -t johnrattz/multi-client ./client
  - docker build -t johnrattz/multi-nginx ./nginx
  - docker build -t johnrattz/multi-server ./server
  - docker build -t johnrattz/multi-worker ./worker
  # Log in to the Docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub.
  - docker push johnrattz/multi-client
  - docker push johnrattz/multi-nginx
  - docker push johnrattz/multi-server
  - docker push johnrattz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-166068999731
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY